# Generated by Django 5.1.1 on 2024-10-04 20:09

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.CharField(help_text='Enter a colour for the car', max_length=200)),
                ('year', models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)])),
                ('VIN', models.CharField(max_length=17, unique=True, validators=[django.core.validators.MinLengthValidator(17)])),
                ('mileage', models.IntegerField()),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='garage.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a car make (e.g. Nissan, Honda, Toyota etc.)', max_length=200, unique=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='make_name_case_insensitive_unique', violation_error_message='Make already exists')],
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='garage.make'),
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('taken', models.DateField()),
                ('due_back', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='garage.car')),
            ],
            options={
                'ordering': ['due_back'],
            },
        ),
    ]
