# Generated by Django 5.1.1 on 2024-10-07 17:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_rental_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
