# Generated by Django 5.1.1 on 2024-10-09 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0005_alter_rental_options_rename_due_back_rental_drop_off_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
